language: node_js

node_js:
  - "11"

services:
  - docker
env:
  global:
    - GROUP=deploy.razee.io
    - VERSION=v1alpha2
    - REPO=quay.io/mxpaspa/rrs3-fork
script:
  # Audit npm packages. Fail build whan a PR audit fails, otherwise report the vulnerability and proceed.
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --low; else npx audit-ci --low || true; fi
  - npm run lint
  - npm test
  - docker build --rm -t "${REPO}:${TRAVIS_COMMIT}" --build-arg GROUP=${GROUP} --build-arg VERSION=${VERSION} .
  - if [ -n "${TRAVIS_TAG}" ]; then docker tag ${REPO}:${TRAVIS_COMMIT} ${REPO}:${TRAVIS_TAG}; fi
  - if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then npm version --no-git-tag-version "${TRAVIS_TAG}"; fi
  - docker images
  - ./build/process-template.sh kubernetes/RemoteResourceS3/resource.yaml >/tmp/resource.yaml

before_deploy:
  - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io

deploy:
  # Deploy alpha builds
  - provider: script
    script: docker push "${REPO}:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$

  # Deploy released builds
  - provider: script
    script: docker push "${REPO}:${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: releases
    file: /tmp/resource.yaml
    skip_cleanup: true
    api_key:
      secure: "${GITHUB_TOKEN}"
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: npm
    email: "${NPMJS_EMAIL}"
    api_key: "${NPMJS_API_KEY}"
    name: "${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
